name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v1

      - name: Set version
        id: version
        run: |
          echo "$(date +%y%m%d.%H%M)" > VERSION
          echo ::set-output name=version::$(cat VERSION)

      - name: Build & publish
        run: |
          dotnet publish src/MyWeb --output .publish/MyWeb

      - name: Zip
        run: |
          zip -r .publish/MyWeb-$(cat VERSION).zip .publish/MyWeb
          ls -al .publish

      # - name: Create release
      #   id: create-release
      #   uses: actions/create-release@v1.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.version.outputs.version }}
      #     release_name: ${{ steps.version.outputs.version }}
      #     draft: false
      #     prerelease: false

      # - name: Upload assets
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: .publish/MyWeb-${{ steps.version.outputs.version }}.zip
      #     asset_name: MyWeb-${{ steps.version.outputs.version }}.zip
      #     asset_content_type: application/zip
