name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v1

      - name: Set version
        run: |
          echo "::set-env name=VERSION::$(date +%y.%m.%d%H%M)"
          echo "::set-env name=ZIP::MyWeb-$VERSION.zip"

      - name: Build & publish
        run: |
          dotnet publish src/MyWeb --output .publish/MyWeb

      - name: Zip
        run: |
          zip -r .publish/$ZIP .publish/MyWeb

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.$VERSION
          release_name: v.$VERSION
          draft: false
          prerelease: false

      - name: Upload assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .publish/$ZIP
          asset_name: $ZIP
          asset_content_type: application/zip
