name: .NET

on: [push]

jobs:
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm --prefix client ci
          npm --prefix client run build --if-present
        env:
          CI: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: Build with dotnet
        run: dotnet publish src/MyWeb --configuration Release --output X

      - name: Check wwwroot
        run: |
          ls -al X
          ls -al X/wwwroot
